In [362]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [363]:

import time
import numpy as np
import cv2
from matplotlib import pyplot as plt
import os
import csv

from os import listdir
from os.path import isfile, join

In [364]:
train_data_list = []
with open('drive/My Drive/korat_sauce/img_csv.csv') as f_img:
    img_bins = csv.reader(f_img)
    for im in img_bins:
        train_data_list.append(im)
    f_img.close()

# r_bins =  np.array(train_data_list[0][1:33]).astype(np.float)
# g_bins = np.array(train_data_list[0][33:65]).astype(np.float)
# b_bins = np.array(train_data_list[0][65:97]).astype(np.float)




In [365]:
r_bins = []
g_bins = []
b_bins = []
target = []
data_for_train = []
for i in range(len(train_data_list)):
    img_data = np.array(train_data_list[i]).astype(np.float)
    # min_x =  min(img_data) 
    # max_x = max(img_data)
    # for j in range(1,len(img_data)):
    #     img_data[j] = (img_data[j]-min_x)/(max_x-min_x) #normalization
    data_for_train.append(img_data)
    r_bins.append(img_data[1:33])
    g_bins.append(img_data[33:65])
    b_bins.append(img_data[65:97])
    target.append(img_data[0])


bins_order = np.arange(32).astype(np.float)
# for i in range(len(bins_order)):
#     bins_order[i]  = (bins_order[i]-1)/31

**CREATE WEIGHT**

In [366]:
WIL_R = [] # มีทั้งหมด 32 ส่วน แต่ละส่วน ประกอบด้วย 2 row 3 column แต่ต้องสลับ
for i in range(32):
    WIL_R.append(np.random.rand(3,2).astype(np.float) )
WIL_R

[array([[0.24132455, 0.48284493],
        [0.28205079, 0.9722722 ],
        [0.97775288, 0.90426068]]), array([[0.53388467, 0.08908677],
        [0.01782724, 0.82490069],
        [0.3083707 , 0.65624639]]), array([[0.47137923, 0.3254557 ],
        [0.82613709, 0.53193773],
        [0.64460953, 0.88071846]]), array([[0.21317453, 0.7995507 ],
        [0.26228952, 0.77733842],
        [0.76405506, 0.9211286 ]]), array([[0.8148869 , 0.24005574],
        [0.59728499, 0.57985074],
        [0.47183711, 0.38195335]]), array([[0.84032911, 0.39257626],
        [0.01035682, 0.95844422],
        [0.59267393, 0.61727534]]), array([[0.72022657, 0.96935826],
        [0.12161228, 0.68994122],
        [0.44906462, 0.88798534]]), array([[0.36580394, 0.97490031],
        [0.43816585, 0.39713868],
        [0.82910526, 0.03150419]]), array([[0.46244795, 0.41420195],
        [0.6477763 , 0.32306326],
        [0.3241417 , 0.43101521]]), array([[0.08048086, 0.32451202],
        [0.33387803, 0.67876719],
     

In [367]:
WLT_R = [] # มีทั้งหมด 32 ส่วน  แต่ละส่วน ประกอบด้วย 3 row 4 column แต่ต้องสลับ
for i in range(32):
    WLT_R.append(np.random.rand(4,3).astype(np.float) )
WLT_R

[array([[0.72631885, 0.76302545, 0.00172228],
        [0.33347963, 0.05122149, 0.5298455 ],
        [0.27052546, 0.45836597, 0.29385921],
        [0.03240517, 0.49465886, 0.67111076]]),
 array([[0.93697854, 0.59520583, 0.48776818],
        [0.6652757 , 0.3267306 , 0.30232811],
        [0.35334565, 0.04164268, 0.04405207],
        [0.89873242, 0.131164  , 0.16142899]]),
 array([[0.91925191, 0.97326537, 0.1086367 ],
        [0.69799178, 0.39446474, 0.42064923],
        [0.19971171, 0.23362667, 0.64590685],
        [0.11184891, 0.86767961, 0.92528853]]),
 array([[0.12951955, 0.40383892, 0.53555917],
        [0.95094595, 0.83788988, 0.46481003],
        [0.49929258, 0.55290166, 0.6250646 ],
        [0.41121314, 0.08147112, 0.81977902]]),
 array([[0.61643056, 0.89902876, 0.71682896],
        [0.22051621, 0.81896803, 0.12355461],
        [0.0659492 , 0.17440477, 0.54197501],
        [0.40638828, 0.18080263, 0.48806838]]),
 array([[0.98678365, 0.5147703 , 0.54179873],
        [0.62361216, 0.4

**CREATE BIAS**

In [368]:
b_for_WIL_R = np.ones(96).astype(np.float) # 96 จาก 32 จุด โดยแต่ละจุดมี ไป 3 tf_L
b_for_WIL_R

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [369]:
b_for_WLT_R  = np.ones((32,4)).astype(np.float) # 128 เนื่องจากว่า 32 จุด แต่ละจุดไปยัง 4 tf_T
b_for_WLT_R

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**PERCEPTRON**

In [370]:
def perceptron(input_data,weight,bias):
    # print(np.dot(input_data,np.transpose(weight))+bias)
    return np.dot(input_data,np.transpose(weight))+bias

**TRANSFER FUNCTION**

In [371]:
def tf_L1(result_of_summation):
    # print("result_of_summation = ",result_of_summation)
    if(result_of_summation>=0.8):
        return 1
    else:
        return 0

In [372]:
def tf_L2(result_of_summation):
    # print("result_of_summation = ",result_of_summation)
    if(result_of_summation>=0.5):
        return 1
    else:
        return 0

In [373]:
def tf_L3(result_of_summation):
    # print("result_of_summation = ",result_of_summation)
    if(result_of_summation>=0.3):
        return 1
    else:
        return 0

In [374]:
def tf_L2T(result_of_summation):
    #print("result_of_summation = ",result_of_summation)
    for i in range(len(result_of_summation)):
      if(result_of_summation[i]>=2):
          result_of_summation[i] = 1
      else:
          result_of_summation[i] = 0
    return result_of_summation

**TRAIN WEIGHT**

In [375]:
def tr_L(delta_weight_trans,WIL_R,b_for_WIL_R,in_r,w_position,bias_postion):
    #print("w = ",WIL_R[in_r])
    delta_weight_in = (sum(delta_weight_trans)*WIL_R[in_r][w_position])/sum(WIL_R[in_r][w_position])
    WIL_R[in_r][w_position] = WIL_R[in_r][w_position]+delta_weight_in
    b_for_WIL_R[bias_postion] = b_for_WIL_R[bias_postion]+sum(delta_weight_trans)*0.5
    #print('bias delta = ',sum(delta_weight_trans))
    return WIL_R,b_for_WIL_R
    #print("delta = ",delta_weight_in)
    # #error = sum(delta_weight_trans))
    # diff_error = delta_weight_trans*transfer_line
    # print(transfer_line)
    # delta_weight = (diff_error*WIL_R[in_r]) / sum(WIL_R[in_r])*0.1
    # print(delta_weight)
    

In [376]:
def tr_L2T(target,result,WLT_R,b_for_WLT_R,in_r):
    target_array = 0
    if(target == 1):
          target_array = np.array([1,0,0,0]).astype(np.float)
    elif(target == 2):
          target_array = np.array([0,1,0,0]).astype(np.float)
    elif(target == 3):
          target_array = np.array([0,0,1,0]).astype(np.float)
    elif(target == 4):
          target_array = np.array([0,0,0,1]).astype(np.float)

    error = target_array-result
    
    delta_weight = []
    for i in range(len(WLT_R[in_r])):
        delta_weight.append(error[i]*WLT_R[in_r][i] / sum(WLT_R[in_r]))
    
    # print('dleta weight ',delta_weight)
    WLT_R[in_r] = WLT_R[in_r]+delta_weight
    b_for_WLT_R[in_r] = b_for_WLT_R[in_r]+sum(error)*0.5
    #print(WLT_R[in_r])
    #return WLT_R,b_for_WLT_R,error,delta_weight
    return WLT_R,b_for_WLT_R,delta_weight


**LEARN**

In [377]:
def lr_r_bins(input_r,bins_order,WIL_R,WLT_R,b_for_WIL_R,b_for_WLT_R,learn_round):
  round_train = 0
  check_true = 0

  while (True and round_train<learn_round):
    round_train+=1
    check_true = 0

      #หาค่า
      ###################
    for pic_input_r in range(len(input_r)): # จำนวนของภาพในแชลเนลสีแดง
        for in_r in range(len(input_r[0])): # in_r คือ จุด
          #L1
          percept_L1 =  perceptron(np.array([bins_order[in_r],input_r[pic_input_r][in_r]]),WIL_R[in_r][0],b_for_WIL_R[in_r*3]) #in_r*3 มาจากวนให้ถึง 96
          transfer_L1 =  tf_L1(percept_L1)

          #L2
          percept_L2 =  perceptron(np.array([bins_order[in_r],input_r[pic_input_r][in_r]]),WIL_R[in_r][1],b_for_WIL_R[in_r*3+1])
          transfer_L2 =  tf_L2(percept_L2)

          #L3
          percept_L3 =  perceptron(np.array([bins_order[in_r],input_r[pic_input_r][in_r]]),WIL_R[in_r][2],b_for_WIL_R[in_r*3+2])
          transfer_L3 =  tf_L1(percept_L3)

          #type
          percept_type  = perceptron(np.array([transfer_L1,transfer_L2,transfer_L3]),WLT_R[in_r],b_for_WLT_R[in_r])
          transfer_type  = tf_L2T(percept_type)
          print("result for type = ",transfer_type)

          #เช็ค error แล้วค่อยดำเนินการอัปเดต
          target_array = 0
          if(target[pic_input_r] == 1):
                target_array = np.array([1,0,0,0]).astype(np.float)
          elif(target[pic_input_r] == 2):
                target_array = np.array([0,1,0,0]).astype(np.float)
          elif(target[pic_input_r] == 3):
                target_array = np.array([0,0,1,0]).astype(np.float)
          elif(target[pic_input_r] == 4):
                target_array = np.array([0,0,0,1]).astype(np.float)

          valid_round = 0
          #ถ้าไม่ถูกต้อง อัปเดต
          while not(np.array_equal(target_array,transfer_type)):
              valid_round += 1
              if valid_round == 1000:
                  valid_round =0
                  break
              WLT_R,b_for_WLT_R,delta_weight = tr_L2T(target[pic_input_r],transfer_type,WLT_R,b_for_WLT_R,in_r)
              delta_weight_trans =  np.transpose(delta_weight) 
              
              WIL_R,b_for_WIL_R  = tr_L(delta_weight_trans[0],WIL_R,b_for_WIL_R,in_r,0,in_r*3)
              WIL_R,b_for_WIL_R  = tr_L(delta_weight_trans[1],WIL_R,b_for_WIL_R,in_r,1,in_r*3+1)
              WIL_R,b_for_WIL_R  = tr_L(delta_weight_trans[2],WIL_R,b_for_WIL_R,in_r,2,in_r*3+2)

              percept_L1 =  perceptron(np.array([bins_order[in_r],input_r[pic_input_r][in_r]]),WIL_R[in_r][0],b_for_WIL_R[in_r*3]) #in_r*3 มาจากวนให้ถึง 96
              transfer_L1 =  tf_L1(percept_L1)

              #L2
              percept_L2 =  perceptron(np.array([bins_order[in_r],input_r[pic_input_r][in_r]]),WIL_R[in_r][1],b_for_WIL_R[in_r*3+1])
              transfer_L2 =  tf_L2(percept_L2)

              #L3
              percept_L3 =  perceptron(np.array([bins_order[in_r],input_r[pic_input_r][in_r]]),WIL_R[in_r][2],b_for_WIL_R[in_r*3+2])
              transfer_L3 =  tf_L1(percept_L3)

              #type
              percept_type  = perceptron(np.array([transfer_L1,transfer_L2,transfer_L3]),WLT_R[in_r],b_for_WLT_R[in_r])
              transfer_type  = tf_L2T(percept_type)
              print("result for type = ",transfer_type,"   real result = ",target_array)
          

          # break
        #break
    #break
        ###################





In [378]:
lr_r_bins(r_bins,bins_order,WIL_R,WLT_R,b_for_WIL_R,b_for_WLT_R,200)

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.]    real result =  [0. 0. 0. 1.]
result for type =  [1. 0. 0. 0.] 

KeyboardInterrupt: ignored

In [ ]:
WIL_R

In [ ]:
WLT_R

In [ ]:
b_for_WIL_R

In [ ]:
b_for_WLT_R