In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:

import time
import numpy as np
import cv2
from matplotlib import pyplot as plt
import os
import csv

from os import listdir
from os.path import isfile, join

In [ ]:
train_data_list = []
with open('drive/My Drive/korat_sauce/img_csv.csv') as f_img:
    img_bins = csv.reader(f_img)
    for im in img_bins:
        train_data_list.append(im)
    f_img.close()

# r_bins =  np.array(train_data_list[0][1:33]).astype(np.float)
# g_bins = np.array(train_data_list[0][33:65]).astype(np.float)
# b_bins = np.array(train_data_list[0][65:97]).astype(np.float)




In [ ]:
r_bins = []
g_bins = []
b_bins = []
target = []
data_for_train = []
for i in range(len(train_data_list)):
    img_data = np.array(train_data_list[i]).astype(np.float)
    min_x =  min(img_data) 
    max_x = max(img_data)
    for j in range(1,len(img_data)):
        img_data[j] = (img_data[j]-min_x)/(max_x-min_x) #normalization
    data_for_train.append(img_data)
    r_bins.append(img_data[1:33])
    g_bins.append(img_data[33:65])
    b_bins.append(img_data[65:97])
    target.append(img_data[0])


bins_order = np.arange(32).astype(np.float)
for i in range(len(bins_order)):
    bins_order[i]  = (bins_order[i]-1)/31

**CREATE WEIGHT**

In [ ]:
w_32t16 = np.random.rand(16,32).astype(np.float) 
w_32t16

array([[1.64290732e-01, 9.13720414e-01, 6.04888922e-01, 1.31704087e-01,
        5.01367806e-01, 5.54465173e-01, 6.16168110e-02, 3.98641228e-01,
        1.23763889e-01, 9.74585686e-01, 1.44739798e-01, 8.39554709e-01,
        6.26809816e-01, 1.90030694e-02, 5.90266709e-01, 8.49167611e-01,
        8.44499226e-01, 9.94318177e-01, 6.18792198e-01, 7.86675756e-01,
        8.18206271e-01, 2.03131641e-01, 6.59458547e-01, 3.21046973e-01,
        8.76894241e-01, 3.32107434e-01, 8.27126619e-01, 9.25626303e-01,
        1.65895141e-01, 2.13512093e-01, 2.14826597e-01, 4.28381872e-02],
       [1.64514439e-01, 3.02813842e-01, 2.88759954e-01, 1.80514081e-01,
        7.22885133e-01, 4.66541316e-01, 6.72101136e-02, 4.14367203e-01,
        8.49527225e-01, 7.71286310e-01, 3.37765395e-01, 7.53315675e-01,
        2.48044690e-01, 1.95565076e-01, 9.98157876e-01, 4.05369087e-01,
        2.30631424e-02, 1.67654750e-01, 2.49585247e-01, 7.24031151e-02,
        8.63022458e-01, 8.74352944e-01, 5.10593035e-01, 8.46596

In [ ]:
w_16t4 = np.random.rand(4,16).astype(np.float) 
w_16t4

array([[0.77140515, 0.45979802, 0.67372412, 0.90860336, 0.57828888,
        0.31611775, 0.86783181, 0.47086544, 0.98279992, 0.19942809,
        0.86354432, 0.48698591, 0.18533833, 0.75741633, 0.26139782,
        0.67220091],
       [0.33851199, 0.03130677, 0.34714317, 0.14677584, 0.24198326,
        0.38498056, 0.97402442, 0.14231007, 0.6620716 , 0.97007404,
        0.2946222 , 0.8798768 , 0.68495677, 0.2618171 , 0.34720931,
        0.80433585],
       [0.23396969, 0.37599549, 0.44597918, 0.64150039, 0.09467593,
        0.52925324, 0.01927811, 0.66928965, 0.87317136, 0.41765043,
        0.31751541, 0.76581295, 0.92289048, 0.62353537, 0.01212169,
        0.49695211],
       [0.58844535, 0.02068516, 0.24836095, 0.59724116, 0.95447918,
        0.69244072, 0.46737214, 0.82020047, 0.49957517, 0.92179888,
        0.78289878, 0.85361425, 0.27067612, 0.3599656 , 0.6489619 ,
        0.2916432 ]])

In [ ]:
w_4t4 = np.random.rand(4,4).astype(np.float) 
w_4t4

array([[0.47126543, 0.90429795, 0.70629214, 0.53446527],
       [0.88360652, 0.42664091, 0.58021346, 0.72713008],
       [0.30666168, 0.12342398, 0.09001804, 0.63795569],
       [0.53138884, 0.92248451, 0.99090535, 0.81577482]])

**CREATE BIAS**

In [ ]:
# b_32t16 = np.ones(32,16).astype(np.float)
# b_16t4 = np.ones(16,4).astype(np.float)
bias = 0

**PERCEPTRON**

In [ ]:
def perceptron(input_data,weight,bias):
    # print(np.dot(input_data,np.transpose(weight))+bias)
    return np.dot(input_data,np.transpose(weight))+bias

**TRANSFER FUNCTION**

**TRAIN WEIGHT**

In [ ]:
def tr(target,result):


**LEARN**

In [ ]:
a = perceptron(r_bins[0],w_32t16,bias)
print(a)
print(np.arctan(a))
a= np.arctan(a)
b = perceptron(a,w_16t4,bias)
print(b)
b = np.arctan(b)
print(b)
c = perceptron(b,w_4t4,bias)
print(c)
print(np.arctan(c))

[3.78754298 3.02300527 3.86342755 3.47749502 3.5369254  3.63911602
 3.16998808 3.82567564 3.11015527 3.51099352 4.4486553  3.45321978
 4.03945994 3.29997421 3.99850858 3.63768362]
[1.31266333 1.25133053 1.31751745 1.29078802 1.29525656 1.30262349
 1.26521835 1.3151251  1.25970851 1.29332396 1.3496846  1.28892193
 1.32811748 1.27655959 1.3257299  1.30252289]
[12.25077472  9.73705191  9.6506485  11.74236485]
[1.48934941 1.46845464 1.46754484 1.48583959]
[3.86044446 3.8743896  1.71797424 4.81235887]
[1.31733001 1.31820393 1.04365684 1.36591377]


In [ ]:
print(a*(180/np.pi))
print(b*(180/np.pi))

[75.21006868 71.69595799 75.4881893  73.95670596 74.2127345  74.63482853
 72.49167189 75.35111764 72.17598129 74.10200473 77.33123149 73.84978653
 76.09552626 73.14147695 75.95872817 74.6290643 ]
[85.33343545 84.13625346 84.08412533 85.13233774]


In [ ]:
180/np.pi

57.29577951308232

In [ ]:
np.arctan(34.92818363)



1.542173970822402

In [ ]:
print(target[12])
a = perceptron(r_bins[4],w_32t16,bias)
print(a)
print(np.arctan(a))
a= np.arctan(a)
b = perceptron(a,w_16t4,bias)
print(b)
# b = np.arctan(b)
# print(b)


2.0
[6.32850197 5.28517695 5.97726621 5.41558172 5.84909435 5.58987049
 4.83450668 5.65606856 5.58715188 5.83484483 6.67420296 5.03168373
 6.38049083 5.58343336 5.66839918 5.7660834 ]
[1.41407684 1.38379849 1.40503095 1.38820071 1.40146683 1.3937739
 1.3668265  1.39580347 1.39368955 1.40106119 1.42207203 1.37461199
 1.41533325 1.39357405 1.39617644 1.39907641]
[13.1992985  10.47388702 10.39283748 12.59851673]


In [ ]:
print(np.tan(b))
print(np.arctan(b))

[0.73360872 1.73972224 1.45314599 0.03215719]
[1.49517918 1.47560932 1.47487152 1.49158797]


In [ ]:
import numpy as np
a = np.zeros(4)
a