In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import numpy as np
import cv2
import os
import imutils

from sklearn.metrics import classification_report 
from sklearn.metrics import f1_score ,accuracy_score

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D

from os import listdir
from os.path import isfile, join
import tensorflow

In [2]:
batch_size = 32
num_classes = 4
#epochs = 16
data_augmentation = True
num_predictions = 20
width = 150
height = 150
#images = np.empty((0, 150,150,3))
labels = []
rawImage = []

In [3]:
model9 = Sequential()

model9.add(Conv2D(32, (3, 3), padding='same', input_shape=(150, 150, 3)))
model9.add(Activation('relu'))
model9.add(Conv2D(32, (3, 3), padding='same', input_shape=(150, 150, 3)))
model9.add(Activation('relu'))
model9.add(MaxPooling2D(pool_size=(2, 2)))

model9.add(Conv2D(64, (3, 3), padding='same'))
model9.add(Activation('relu'))
model9.add(MaxPooling2D(pool_size=(2, 2)))

model9.add(Conv2D(128, (3, 3), padding='same'))
model9.add(Activation('relu'))
model9.add(MaxPooling2D(pool_size=(2, 2)))

model9.add(Flatten())
model9.add(Dense(128))
model9.add(Activation('relu'))
model9.add(Dropout(0.5))
model9.add(Dense(4))
model9.add(Activation('sigmoid'))
model9.compile(loss="binary_crossentropy",
              optimizer="rmsprop",
              metrics=["accuracy"])
model9.load_weights("/content/drive/My Drive/korat_sauce/train_sauce9.h5")

In [4]:
 from google.colab import drive
drive.mount('/content/drive')

!unzip drive/"My Drive"/korat_sauce/count_pic3.zip

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Archive:  drive/My Drive/korat_sauce/count_pic3.zip
   creating: pic_from_count/
  inflating: pic_from_count/all.0.ocean.jpg  
  inflating: pic_from_count/all.1.ocean.jpg  
  inflating: pic_from_count/all.10.zapnuerchick.jpg  
  inflating: pic_from_count/all.11.ocean.jpg  
  inflating: pic_from_count/all.12.maeyupa.jpg  
  inflating: pic_from_count/all.13.zapnuerchick.jpg  
  inflating: pic_from_count/all.14.zapnuerchick.jpg  
  inflating: pic_from_count/all.15.ocean.jpg  
  inflating: pic_from_count/all.16.zapnuerchick.jpg  
  inflating: pic_from_count/all.17.ocean.jpg  
  inflating: pic_from_count/all.18.maeyupa.jpg  
  inflating: pic_from_count/all.19.ocean.jpg  
  inflating: pic_from_count/all.2.zapnuer.jpg  
  inflating: pic_from_count/all.20.zapnuerchick.jpg  
  inflating: pic_from_count/all.21.zapnuer.jpg  
  inflating: pic_from_count/all.22.ocean.jpg 

In [5]:
mypath_test = 'pic_from_count/'
imagePaths_test = [mypath_test+f for f in listdir(mypath_test) if isfile(join(mypath_test, f))]

In [6]:
imagePaths_test.sort()

In [7]:
#######
for (i, img_path) in enumerate(imagePaths_test):
  #img_path = 'all_sauce/ocean.'+str(i)+'.jpg'
  img_list = []
  image = cv2.imread(img_path)
  image = cv2.resize(image, (width,height))
  img_list.append(image)
  img_list = np.array(img_list)
  img_list = img_list.astype('float32')


  # Remember that the model was trained on inputs
  # that were preprocessed in the following way:
  img_list /= 255.
  # Its shape is (1, 150, 150, 3)

  print(img_list.shape)
  print(img_path)

  #plt.imshow(img_list[0])
  #plt.imshow(X_test[0])
  #plt.show()

  prediction = model9.predict(np.array([img_list[0]]))
  #prediction = model.predict(np.array([X_test[0]]))
  print(prediction[0])
  print(max(prediction[0]))
  y_classes = prediction.argmax(axis=-1)
  print(y_classes)
  print("#####")

(1, 150, 150, 3)
pic_from_count/all.0.ocean.jpg
[5.2652034e-05 9.9991333e-01 3.7291918e-06 4.4772069e-06]
0.99991333
[1]
#####
(1, 150, 150, 3)
pic_from_count/all.1.ocean.jpg
[1.0951408e-12 1.0000000e+00 2.8534061e-19 5.5106615e-14]
1.0
[1]
#####
(1, 150, 150, 3)
pic_from_count/all.10.zapnuerchick.jpg
[2.9796362e-03 1.9312706e-06 1.8748164e-02 9.8091257e-01]
0.98091257
[3]
#####
(1, 150, 150, 3)
pic_from_count/all.11.ocean.jpg
[1.4477918e-18 1.0000000e+00 2.7238134e-31 3.3110740e-24]
1.0
[1]
#####
(1, 150, 150, 3)
pic_from_count/all.12.maeyupa.jpg
[9.9999726e-01 1.0058481e-07 4.9574416e-14 1.5223844e-09]
0.99999726
[0]
#####
(1, 150, 150, 3)
pic_from_count/all.13.zapnuerchick.jpg
[1.3371706e-03 6.5444483e-06 2.0681322e-03 9.9349809e-01]
0.9934981
[3]
#####
(1, 150, 150, 3)
pic_from_count/all.14.zapnuerchick.jpg
[8.161932e-03 7.892979e-05 9.443092e-05 9.886303e-01]
0.9886303
[3]
#####
(1, 150, 150, 3)
pic_from_count/all.15.ocean.jpg
[0.6682952  0.08924267 0.00186759 0.14687827]
0.668295

In [20]:
error_path = []
pic_true = 0
pic_false = 0
#######
for (i, img_path) in enumerate(imagePaths_test):
  #img_path = 'all_sauce/ocean.'+str(i)+'.jpg'
  label = img_path.split('/')[1].split('.')[2]
  img_list = []
  image = cv2.imread(img_path)
  image = cv2.resize(image, (width,height))
  img_list.append(image)
  img_list = np.array(img_list)
  img_list = img_list.astype('float32')


  # Remember that the model was trained on inputs
  # that were preprocessed in the following way:
  img_list /= 255.
  # Its shape is (1, 150, 150, 3)

  #print(img_list.shape)
  #print(img_path)

  #plt.imshow(img_list[0])
  #plt.imshow(X_test[0])
  #plt.show()

  prediction = model9.predict(np.array([img_list[0]]))
  #prediction = model.predict(np.array([X_test[0]]))
  #print(prediction[0])
  #print(max(prediction[0]))
  y_classes = prediction.argmax(axis=-1)
  if(label == "maeyupa"):
    if(y_classes[0]==0):
      pic_true+=1
    else:
      pic_false+=1
      error_path.append(img_path)
  elif(label == "ocean"):
    if(y_classes[0]==1):
      pic_true+=1
    else:
      pic_false+=1
      error_path.append(img_path)
  elif(label == "zapnuer"):
    if(y_classes[0]==2):
      pic_true+=1
    else:
      pic_false+=1
      error_path.append(img_path)
  elif(label == "zapnuerchick"):
    if(y_classes[0]==3):
      pic_true+=1
    else:
      pic_false+=1
      error_path.append(img_path)

  #print(y_classes)
  #print("#####")
print("summary ture = ",pic_true," ,false = ",pic_false)
for i  in error_path:
  print(i)

summary ture =  84  ,false =  15
pic_from_count/all.15.ocean.jpg
pic_from_count/all.24.maeyupa.jpg
pic_from_count/all.39.zapnuer.jpg
pic_from_count/all.43.maeyupa.jpg
pic_from_count/all.5.maeyupa.jpg
pic_from_count/all.52.maeyupa.jpg
pic_from_count/all.60.ocean.jpg
pic_from_count/all.61.ocean.jpg
pic_from_count/all.65.zapnuerchick.jpg
pic_from_count/all.74.ocean.jpg
pic_from_count/all.88.ocean.jpg
pic_from_count/all.89.ocean.jpg
pic_from_count/all.91.ocean.jpg
pic_from_count/all.92.ocean.jpg
pic_from_count/all.96.zapnuer.jpg
