In [20]:
import numpy as np

In [62]:
n = np.array([[1, 2, 3]])

In [49]:
a = [np.array(np.array([1,2,3]))]
b = [np.array(np.array([4,5,6]))]
c = np.array([7,8,9])
d = np.array([10,11,12])
e = [[13,14,15]]
f = [[16,17,18]]

In [55]:
n = np.append(n,a)
n

array([ 7.,  8.,  9., 10., 11., 12.,  1.,  2.,  3.])

In [24]:
n = np.append(n,b)
n

array([1., 2., 3., 4., 5., 6.])

In [25]:
n

array([1., 2., 3., 4., 5., 6.])

In [63]:
n = np.append(n,[[7, 8, 9]], axis=0)
n

array([[1, 2, 3],
       [7, 8, 9]])

In [53]:
n = np.append(n,[d], axis=0)
n

array([ 7.,  8.,  9., 10., 11., 12.])

In [54]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
a = []
b = np.array([1,2,3])
c = np. array([4,5,6])

In [69]:
b[0]

7

In [66]:
a.append(b)
a.append(c)
a

[array([1, 2, 3]), array([4, 5, 6])]

In [68]:
b = np.array([7,28,9])
a

[array([1, 2, 3]), array([4, 5, 6])]

In [76]:
class  s:
  def __init__(self):
      self.a = np.array([1,2,3])
      self.a_list = []
  def learn(self):
      for i in range(5):
        self.a[0]+=1
        self.a[1]+=1
        self.a[2]+=1
        self.a_list.append(self.a.copy())
        print(self.a_list)
m = s()
m.learn()

[array([2, 3, 4])]
[array([2, 3, 4]), array([3, 4, 5])]
[array([2, 3, 4]), array([3, 4, 5]), array([4, 5, 6])]
[array([2, 3, 4]), array([3, 4, 5]), array([4, 5, 6]), array([5, 6, 7])]
[array([2, 3, 4]), array([3, 4, 5]), array([4, 5, 6]), array([5, 6, 7]), array([6, 7, 8])]
