In [ ]:

import time
import numpy as np
import cv2
import scipy.special
import matplotlib.pyplot as plt
import os
import csv

from os import listdir
from os.path import isfile, join
import pandas
from scipy import ndimage
import random

In [ ]:
# neural network class definition
class neuralNetwork :

    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes,learningrate,hiddenlayer) :

        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes

        self.num_hiddenlayer = hiddenlayer

        #set weight
        self.set_w  = []
        #self.w = np.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.inodes))
        self.set_w.append(np.random.normal(0.0, pow(self.inodes, -0.5),(self.hnodes, self.inodes)))
        for i in range(self.num_hiddenlayer-1):
            self.set_w.append(np.random.normal(0.0, pow(self.hnodes, -0.5),(self.hnodes, self.hnodes)))
        self.set_w.append(np.random.normal(0.0, pow(self.hnodes, -0.5),(self.onodes, self.hnodes)))
        self.set_w = np.array(self.set_w)

        # learning rate
        self.lr = learningrate
        self.bias = []
        for i in range(self.num_hiddenlayer+1):
            self.bias.append(1)
        self.bias = np.array(self.bias)
        

        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        #self.derivative_function = lambda x: 1 if x>0 else 0 if x==0 else -1

        pass
   
    

    # train the neural network
    def train(self, inputs_list, targets_list) :
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        # print('targets = ', targets)

        result_each_layer_set = []
        # w_dot_input = np.dot(self.w, inputs)
        # outputs = self.activation_function(w_dot_input+1)
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(self.num_hiddenlayer):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        

        # output layer error is the (target actual)
        #output_errors = targets-outputs
        error_set = []
        output_errors = targets-result_each_layer_set[-1]
        
        error_set.append(output_errors)
        for i in range(self.num_hiddenlayer):
            error_set.append(np.dot(self.set_w[0-(i+1)].T,error_set[i]))
        
        # print(error_set)
        # print(self.set_w)



        
        
        # update the weights 
       
        # self.w += self.lr * np.dot((output_errors*outputs * (1.0-outputs)),np.transpose(inputs)) 
        for i in range(len(error_set)-1):
            self.set_w[0-(i+1)] += self.lr * np.dot((error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)])), np.transpose(result_each_layer_set[0-(i+2)]))
            self.bias[0-(i+1)] +=  self.lr*self.bias[0-(i+1)] *sum(error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)]))
        self.set_w[0] += self.lr * np.dot((error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0])), np.transpose(inputs))
        self.bias[0] +=  self.lr *self.bias[0] *sum(error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0]))
        


        # print("*********")
        pass

    # query the neural network
    def query(self, inputs_list) :

        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T


        # output = np.dot(self.w, inputs)

        # # calculate the signals emerging 
        # final_outputs = self.activation_function(output)

        result_each_layer_set = []
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(self.num_hiddenlayer):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        
        final_outputs = result_each_layer_set[-1]

        return final_outputs
    
   
    # def write_weight(self) :
    #     f = open('who.txt','w',encoding='utf-8')
    #     f.write(str(self.who))
    #     f.close()
    #     f = open('wih.txt','w',encoding='utf-8')
    #     f.write(str(self.wih))
    #     f.close()
    #     print('already write!! ')
        

In [ ]:

accuracy_each_epochs = []

input_nodes = 5
output_nodes = 2
hidden_nodes = 3

learning_rate = 0.1
hidden_layers = 1


###

n = neuralNetwork(input_nodes,hidden_nodes,output_nodes,learning_rate,hidden_layers)
inputs = np.array([0.1,0.2,0.3,0.4,0.5])
targets = np.array([0,1])


n.train(inputs, targets)
n.query(inputs)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


array([[0.47833741],
       [0.49939036]])

In [ ]:
a = np.array([1,2,3,4,5])
#a = np.array([[1,2],[3,4]])
b = np.array([1,2])
# np.dot(np.transpose(a),b)
# np.dot(a,b)

In [ ]:

a = np.array([[0.1],[0.2],[0.3]])
b = np.array([0.7])
#np.dot(np.transpose(a),b)
np.dot(a,b)


array([0.07, 0.14, 0.21])

In [ ]:
a.T

array([1, 2, 3, 4, 5])

In [ ]:
[array([[-0.8752797 ],
       [ 0.12660552]]), 
 
 array([[ 0.27754787],
       [-1.03079466],
       [-0.24533705]])
 
 ]

In [ ]:
[array([[-0.32843877, -0.49393965, -0.62971025, -0.3760411 , -0.13011328],
       [ 0.13540883,  0.577287  ,  0.17662612,  0.10087441,  0.36847161],
       [ 0.33135072,  0.48795237,  0.4093101 ,  0.7552548 , -0.02359004]])
 array([[-0.16425235, -0.16080116, -0.84859079],
       [ 0.1088883 , -0.57864488, -0.58643546]])]

In [ ]:
[array([[-0.73319296],
       [ 0.26574069]]), 
 
 
 array([[ 0.63166848],
       [-0.19391707],
       [-0.40134137]]),
 
 
  array([[-0.2196363 ],
       [-0.22702633],
       [-0.11043681],
       [ 0.19985197],
       [-0.32806212]])]

In [ ]:
# neural network class definition
class neuralNetwork :

    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes,learningrate,hiddenlayer) :

        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes

        self.num_hiddenlayer = hiddenlayer

        #set weight
        self.set_w  = []
        #self.w = np.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.inodes))
        # self.set_w.append(np.random.normal(0.0, pow(self.inodes, -0.5),(self.hnodes, self.inodes)))
        # for i in range(self.num_hiddenlayer-1):
        #     self.set_w.append(np.random.normal(0.0, pow(self.hnodes, -0.5),(self.hnodes, self.hnodes)))
        # self.set_w.append(np.random.normal(0.0, pow(self.hnodes, -0.5),(self.onodes, self.hnodes)))
        # self.set_w = np.array(self.set_w)
        self.set_w.append(np.random.normal(0.0, pow(self.inodes, -0.5),(self.hnodes[0], self.inodes)))
        for i in range(1,len(self.hnodes)):
            self.set_w.append(np.random.normal(0.0, pow(self.hnodes[i-1], -0.5),(self.hnodes[i], self.hnodes[i-1])))
        self.set_w.append(np.random.normal(0.0, pow(self.hnodes[-1], -0.5),(self.onodes, self.hnodes[-1])))
        self.set_w = np.array(self.set_w)

        # learning rate
        self.lr = learningrate
        self.bias = []
        for i in range(self.num_hiddenlayer+1):
            self.bias.append(1)
        self.bias = np.array(self.bias)
        

        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        #self.derivative_function = lambda x: 1 if x>0 else 0 if x==0 else -1

        pass
   
    

    # train the neural network
    def train(self, inputs_list, targets_list) :
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        # print('targets = ', targets)

        result_each_layer_set = []
        # w_dot_input = np.dot(self.w, inputs)
        # outputs = self.activation_function(w_dot_input+1)
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(self.num_hiddenlayer):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        

        # output layer error is the (target actual)
        #output_errors = targets-outputs
        error_set = []
        output_errors = targets-result_each_layer_set[-1]
        
        error_set.append(output_errors)
        for i in range(self.num_hiddenlayer):
            error_set.append(np.dot(self.set_w[0-(i+1)].T,error_set[i]))
        
        # print(error_set)
        # print(self.set_w)



        
        
        # update the weights 
       
        # self.w += self.lr * np.dot((output_errors*outputs * (1.0-outputs)),np.transpose(inputs)) 
        for i in range(len(error_set)-1):
            self.set_w[0-(i+1)] += self.lr * np.dot((error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)])), np.transpose(result_each_layer_set[0-(i+2)]))
            self.bias[0-(i+1)] +=  self.lr*self.bias[0-(i+1)] *sum(error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)]))
        self.set_w[0] += self.lr * np.dot((error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0])), np.transpose(inputs))
        self.bias[0] +=  self.lr *self.bias[0] *sum(error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0]))
        


        # print("*********")
        pass

    # query the neural network
    def query(self, inputs_list) :

        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T


        # output = np.dot(self.w, inputs)

        # # calculate the signals emerging 
        # final_outputs = self.activation_function(output)

        result_each_layer_set = []
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(self.num_hiddenlayer):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        
        final_outputs = result_each_layer_set[-1]

        return final_outputs
    
   
    # def write_weight(self) :
    #     f = open('who.txt','w',encoding='utf-8')
    #     f.write(str(self.who))
    #     f.close()
    #     f = open('wih.txt','w',encoding='utf-8')
    #     f.write(str(self.wih))
    #     f.close()
    #     print('already write!! ')
        


In [ ]:
# neural network class definition
class neuralNetwork :

    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes,learningrate,send_weight_state = False,weight = 0) :


        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes

        self.set_w  = []
        if (send_weight_state):
            self.set_w = weight
        #set weight
        else:
            #self.w = np.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.inodes))
            self.set_w.append(np.random.normal(0.0, pow(self.inodes, -0.5),(self.hnodes[0], self.inodes)))
            for i in range(1,len(self.hnodes)):
                self.set_w.append(np.random.normal(0.0, pow(self.hnodes[i-1], -0.5),(self.hnodes[i], self.hnodes[i-1])))
            self.set_w.append(np.random.normal(0.0, pow(self.hnodes[-1], -0.5),(self.onodes, self.hnodes[-1])))
        self.set_w = np.array(self.set_w)

        # learning rate
        self.lr = learningrate
        self.bias = []
        for i in range(len(self.hnodes)+1):
            self.bias.append(1)
        self.bias = np.array(self.bias)
        

        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        #self.derivative_function = lambda x: 1 if x>0 else 0 if x==0 else -1

        pass
   
    

    # train the neural network
    def train(self, inputs_list, targets_list) :
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        # print('targets = ', targets)

        result_each_layer_set = []
        # w_dot_input = np.dot(self.w, inputs)
        # outputs = self.activation_function(w_dot_input+1)
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(len(self.hnodes)):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        

        # output layer error is the (target actual)
        #output_errors = targets-outputs
        error_set = []
        output_errors = targets-result_each_layer_set[-1]
        
        error_set.append(output_errors)
        for i in range(len(self.hnodes)):
            error_set.append(np.dot(self.set_w[0-(i+1)].T,error_set[i]))
        
        # print(error_set)
        # print(self.set_w)



        
        
        # update the weights 
       
        # self.w += self.lr * np.dot((output_errors*outputs * (1.0-outputs)),np.transpose(inputs)) 
        for i in range(len(error_set)-1):
            self.set_w[0-(i+1)] += self.lr * np.dot((error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)])), np.transpose(result_each_layer_set[0-(i+2)]))
            self.bias[0-(i+1)] +=  self.lr*self.bias[0-(i+1)] *sum(error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)]))
        self.set_w[0] += self.lr * np.dot((error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0])), np.transpose(inputs))
        self.bias[0] +=  self.lr *self.bias[0] *sum(error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0]))
        


        # print("*********")
        pass

    # query the neural network
    def query(self, inputs_list) :

        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T


        # output = np.dot(self.w, inputs)

        # # calculate the signals emerging 
        # final_outputs = self.activation_function(output)

        result_each_layer_set = []
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(len(self.hnodes)):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        
        final_outputs = result_each_layer_set[-1]

        return final_outputs
    
   
    # def write_weight(self) :
    #     f = open('who.txt','w',encoding='utf-8')
    #     f.write(str(self.who))
    #     f.close()
    #     f = open('wih.txt','w',encoding='utf-8')
    #     f.write(str(self.wih))
    #     f.close()
    #     print('already write!! ')
        

In [ ]:
# neural network class definition
class neuralNetwork :

    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes,learningrate,send_weight_state = False,weight = 0) :


        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes

        self.set_w  = []
        if (send_weight_state):
            self.set_w = weight
        #set weight
        else:
          #self.w = np.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.inodes))
          self.set_w.append(np.random.normal(0.0, pow(self.inodes, -0.5),(self.hnodes[0], self.inodes)))
          for i in range(1,len(self.hnodes)):
              self.set_w.append(np.random.normal(0.0, pow(self.hnodes[i-1], -0.5),(self.hnodes[i], self.hnodes[i-1])))
          self.set_w.append(np.random.normal(0.0, pow(self.hnodes[-1], -0.5),(self.onodes, self.hnodes[-1])))
          self.set_w = np.array(self.set_w)

        # learning rate
        self.lr = learningrate
        self.bias = []
        for i in range(len(self.hnodes)+1):
            self.bias.append(1)
        self.bias = np.array(self.bias)
        

        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        #self.derivative_function = lambda x: 1 if x>0 else 0 if x==0 else -1

        pass
   
    

    # train the neural network
    def train(self, inputs_list, targets_list) :
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        # print('targets = ', targets)

        result_each_layer_set = []
        # w_dot_input = np.dot(self.w, inputs)
        # outputs = self.activation_function(w_dot_input+1)
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(len(self.hnodes)):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        

        # output layer error is the (target actual)
        #output_errors = targets-outputs
        error_set = []
        output_errors = targets-result_each_layer_set[-1]
        
        error_set.append(output_errors)
        for i in range(len(self.hnodes)):
            error_set.append(np.dot(self.set_w[0-(i+1)].T,error_set[i]))
        
        # print(error_set)
        # print(self.set_w)



        
        
        # update the weights 
       
        # self.w += self.lr * np.dot((output_errors*outputs * (1.0-outputs)),np.transpose(inputs)) 
        for i in range(len(error_set)-1):
            self.set_w[0-(i+1)] += self.lr * np.dot((error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)])), np.transpose(result_each_layer_set[0-(i+2)]))
            self.bias[0-(i+1)] +=  self.lr*self.bias[0-(i+1)] *sum(error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)]))
        self.set_w[0] += self.lr * np.dot((error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0])), np.transpose(inputs))
        self.bias[0] +=  self.lr *self.bias[0] *sum(error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0]))
        


        # print("*********")
        pass

    # query the neural network
    def query(self, inputs_list) :

        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T


        # output = np.dot(self.w, inputs)

        # # calculate the signals emerging 
        # final_outputs = self.activation_function(output)

        result_each_layer_set = []
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(len(self.hnodes)):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        
        final_outputs = result_each_layer_set[-1]

        return final_outputs
    
   
    # def write_weight(self) :
    #     f = open('who.txt','w',encoding='utf-8')
    #     f.write(str(self.who))
    #     f.close()
    #     f = open('wih.txt','w',encoding='utf-8')
    #     f.write(str(self.wih))
    #     f.close()
    #     print('already write!! ')
        

In [ ]:
# neural network class definition
class neuralNetwork :

    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes,learningrate,send_weight_state = False,weight = 0,send_bias_state = False,bias_set = 0) :


        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.weight_each_epochs = []
        self.bias_each_epochs = []

        self.set_w  = []
        if (send_weight_state):
            self.set_w = weight
        #set weight
        else:
            #self.w = np.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.inodes))
            self.set_w.append(np.random.normal(0.0, pow(self.inodes, -0.5),(self.hnodes[0], self.inodes)))
            for i in range(1,len(self.hnodes)):
                self.set_w.append(np.random.normal(0.0, pow(self.hnodes[i-1], -0.5),(self.hnodes[i], self.hnodes[i-1])))
            self.set_w.append(np.random.normal(0.0, pow(self.hnodes[-1], -0.5),(self.onodes, self.hnodes[-1])))
        self.set_w = np.array(self.set_w)

        
        # learning rate
        self.lr = learningrate
        self.bias = []
        if (send_bias_state):
            self.bias = bias_set
        else:
            for i in range(len(self.hnodes)+1):
                self.bias.append(1)
        self.bias = np.array(self.bias)
        

        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        #self.derivative_function = lambda x: 1 if x>0 else 0 if x==0 else -1

        pass
   
    

    # train the neural network
    def train(self, inputs_list, targets_list) :
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        # print('targets = ', targets)

        result_each_layer_set = []
        # w_dot_input = np.dot(self.w, inputs)
        # outputs = self.activation_function(w_dot_input+1)
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(len(self.hnodes)):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        

        # output layer error is the (target actual)
        #output_errors = targets-outputs
        error_set = []
        output_errors = targets-result_each_layer_set[-1]
        
        error_set.append(output_errors)
        for i in range(len(self.hnodes)):
            error_set.append(np.dot(self.set_w[0-(i+1)].T,error_set[i]))
        
        # print(error_set)
        # print(self.set_w)



        
        
        # update the weights 
       
        # self.w += self.lr * np.dot((output_errors*outputs * (1.0-outputs)),np.transpose(inputs)) 
        for i in range(len(error_set)-1):
            self.set_w[0-(i+1)] += self.lr * np.dot((error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)])), np.transpose(result_each_layer_set[0-(i+2)]))
            self.bias[0-(i+1)] +=  self.lr*self.bias[0-(i+1)] *sum(error_set[i] * result_each_layer_set[0-(i+1)] * (1.0 - result_each_layer_set[0-(i+1)]))
        self.set_w[0] += self.lr * np.dot((error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0])), np.transpose(inputs))
        self.bias[0] +=  self.lr *self.bias[0] *sum(error_set[-1] * result_each_layer_set[0] * (1.0 - result_each_layer_set[0]))
        self.weight_each_epochs.append(self.set_w.copy())
        self.bias_each_epochs.append(self.bias.copy())



        # print("*********")
        pass

    # query the neural network
    def query(self, inputs_list) :

        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T


        # output = np.dot(self.w, inputs)

        # # calculate the signals emerging 
        # final_outputs = self.activation_function(output)

        result_each_layer_set = []
        result_each_layer_set.append(self.activation_function(np.dot(self.set_w[0], inputs)+self.bias[0]))
        for i in range(len(self.hnodes)):
            result_each_layer_set.append(self.activation_function(np.dot(self.set_w[i+1], result_each_layer_set[i])+self.bias[i+1]))
        
        final_outputs = result_each_layer_set[-1]

        return final_outputs
    
   
    # def write_weight(self) :
    #     f = open('weight.txt','w',encoding='utf-8')
    #     # f.write(str(self.set_w))
    #     for i in self.set_w:
    #         f.write(str(i))
    #         f.write('/')
    #     f.close()
    #     print('already write!! ')
        